### PR TITLE
Add unified_mode to resources and complete Sous-Chefs adoption

### LINKED ISSUE #11: traefik Chef 17 compatibility

### PR DESCRIPTION
**Pull request by damacus**
# Description

Add unified_mode to resources and complete Sous-Chefs adoption.

## Issues Resolved

- #11 

## Check List

- [ ] All tests pass. See TESTING.md for details.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ramereth** [comment]
@damacus this should probably lose the dep on the systemd cookbook and switch to using the `systemd_unit` native resource.

**Comment by damacus** [comment]
> @damacus this should probably lose the dep on the systemd cookbook and switch to using the `systemd_unit` native resource.

Yeah I was trying to do the smallest change possible. I did originally remove the systemd cookbook, but service resource doesn't support a bunch of the system service options. Thanks for the pointer unit pointer 👍🏼

**Comment by ramereth** [comment]
@damacus it looks like the current use-case that this cookbook needs should work with `systemd_unit`.

**Pull request closed without merging**
